#include "radio_train.h"

int radio_train_main()
{
	std::cout << "=== Radio Modulation Classification with 1D CNN ===" << std::endl;
	std::cout << "NN_EPOCHS: " << NN_EPOCHS << std::endl;
	std::cout << "BATCH_SIZE: " << BATCH_SIZE << std::endl;
	std::cout << "NN_PRINT_EVERY: " << NN_PRINT_EVERY << std::endl;

	// Load radio modulation dataset
	std::cout << "Loading radio modulation dataset..." << std::endl;

	Eigen::MatrixXd train_data, test_data;
	Eigen::VectorXi train_labels, test_labels;

	// Load the CSV files generated by generate_radio_dataset.py
	NEURAL_NETWORK::Helpers::ReadCSVMatrix("../../../data/RF/radio_dataset_medium_train_data.csv", train_data);
	NEURAL_NETWORK::Helpers::ReadCSVLabels("../../../data/RF/radio_dataset_medium_train_labels.csv", train_labels);
	NEURAL_NETWORK::Helpers::ReadCSVMatrix("../../../data/RF/radio_dataset_medium_test_data.csv", test_data);
	NEURAL_NETWORK::Helpers::ReadCSVLabels("../../../data/RF/radio_dataset_medium_test_labels.csv", test_labels);

	// Convert labels to double matrix for framework compatibility
	Eigen::MatrixXd y_train(train_labels.size(), 1);
	Eigen::MatrixXd y_test(test_labels.size(), 1);
	for (int i = 0; i < train_labels.size(); i++) 
	{
		y_train(i, 0) = static_cast<double>(train_labels(i));
	}
	for (int i = 0; i < test_labels.size(); i++) 
	{
		y_test(i, 0) = static_cast<double>(test_labels(i));
	}

	std::cout << "Dataset loaded successfully!" << std::endl;
	std::cout << "Training samples: " << train_data.rows() << std::endl;
	std::cout << "Test samples: " << test_data.rows() << std::endl;
	std::cout << "Features per sample: " << train_data.cols() << " (I/Q interleaved)" << std::endl;
	std::cout << "Classes: 16 (PSK: 0-4, QAM: 5-7, Digital: 8-11, Advanced: 12-15)" << std::endl;
	std::cout << "Modulation types: BPSK, QPSK, 8PSK, 16PSK, 64PSK, 16QAM, 32QAM, 64QAM, ASK, 2FSK, 4FSK, 8FSK, GMSK, MSK, AM, FM" << std::endl;

	if (train_data.cols() != 2048)
	 {
		std::cerr << "ERROR: Expected 2048 features but got " << train_data.cols() << std::endl;
		return -1;
	}

	// Data preprocessing - already normalized by Python script, but shuffle for training
	NEURAL_NETWORK::Helpers::ShuffleData(train_data, y_train);

	// Build 1D CNN model for radio signal classification
	std::cout << "\nBuilding 1D CNN architecture..." << std::endl;

	NEURAL_NETWORK::Model model;
	model.Add(std::make_shared<NEURAL_NETWORK::LayerInput>());

	// ===== RESEARCH-GRADE DEEP 1D CNN FOR EXTREME 16-CLASS CHALLENGE =====
	// ARCHITECTURE OPTIMIZED FOR SIGNALS BURIED IN NOISE (-15 TO +5 DB SNR):
	// - Three conv layers (64→128→256) for hierarchical feature extraction
	// - Two dense layers (1024→512→16) for complex classification
	// - Progressive dropout (0.2→0.3→0.35) for deep network regularization
	// - Very low LR (0.00005) + 30 epochs for extreme difficulty convergence
	// - Expected performance: 25-45% (vs 6.25% random baseline)
	std::cout << "Architecture: Input(2048) -> Conv1D(64) -> ReLU -> MaxPool1D -> Conv1D(128) -> ReLU -> MaxPool1D -> Conv1D(256) -> ReLU -> MaxPool1D -> Dropout(0.2) -> Dense(1024) -> ReLU -> Dropout(0.3) -> Dense(512) -> ReLU -> Dropout(0.35) -> Output(16) [EXTREME 16-CLASS CHALLENGE]" << std::endl;

	// ===== RESEARCH-GRADE DEEP 1D CNN FOR EXTREME 16-CLASS CHALLENGE =====
	// Architecture optimized for signals buried in noise (-15 to +5 dB SNR)
	// Three-layer hierarchical feature extraction + two-layer dense classification

	// First 1D Convolution Block - Low-level temporal features
	// Input: 2048 features (1024 time steps × 2 channels I/Q)
	// Output: Extract basic temporal patterns from noisy signals
	model.Add(std::make_shared<NEURAL_NETWORK::Convolution1D>(
		64,        // 64 filters (doubled from 32 for extreme noise)
		9,         // filter length 9 (larger for better noise tolerance)
		1024,      // input_length (time steps)
		2,         // input_channels (I/Q)
		1,         // stride
		1,         // padding
		0.0, 1e-4  // Moderate L2 for deep network
	));
	model.Add(std::make_shared<NEURAL_NETWORK::ActivationReLU>());

	// First MaxPooling1D: reduce temporal dimension by 2
	// Input: 1024 time steps (with padding), 64 channels
	// Output: 512 time steps, 64 channels
	model.Add(std::make_shared<NEURAL_NETWORK::MaxPooling1D>(
		64,         // batch_size (will be adjusted dynamically)
		2,          // pool_size
		1024,       // input_length
		64,         // input_channels (updated from 32 to 64)
		2           // stride
	));

	// Second 1D Convolution Block - Mid-level temporal features
	// Input: 512 time steps, 64 channels
	// Output: Extract more complex temporal patterns
	model.Add(std::make_shared<NEURAL_NETWORK::Convolution1D>(
		128,       // 128 filters (doubled for deeper hierarchy)
		7,         // filter length 7 (optimal balance)
		512,       // input_length (from pooling)
		64,        // input_channels (updated from 32)
		1,         // stride
		1,         // padding
		0.0, 1e-4  // Moderate L2 regularization
	));
	model.Add(std::make_shared<NEURAL_NETWORK::ActivationReLU>());

	// Second MaxPooling1D: further temporal downsampling
	// Input: 512 time steps (with padding), 128 channels
	// Output: 256 time steps, 128 channels
	model.Add(std::make_shared<NEURAL_NETWORK::MaxPooling1D>(
		64,         // batch_size (will be adjusted dynamically)
		2,          // pool_size
		512,        // input_length
		128,        // input_channels (updated from 64 to 128)
		2           // stride
	));

	// Third 1D Convolution Block - High-level feature extraction
	// Input: 256 time steps, 128 channels
	// Output: Extract highest-level temporal patterns for classification
	model.Add(std::make_shared<NEURAL_NETWORK::Convolution1D>(
		256,       // 256 filters (maximum feature extraction)
		5,         // filter length 5 (smaller for high-level features)
		256,       // input_length (from pooling)
		128,       // input_channels
		1,         // stride
		1,         // padding
		0.0, 1e-4  // Consistent L2 regularization
	));
	model.Add(std::make_shared<NEURAL_NETWORK::ActivationReLU>());

	// Third MaxPooling1D: final temporal reduction
	// Input: 256 time steps (with padding), 256 channels
	// Output: 128 time steps, 256 channels
	model.Add(std::make_shared<NEURAL_NETWORK::MaxPooling1D>(
		64,         // batch_size (will be adjusted dynamically)
		2,          // pool_size
		256,        // input_length
		256,        // input_channels
		2           // stride
	));

	// Light dropout after conv layers (reduced for extreme noise conditions)
	model.Add(std::make_shared<NEURAL_NETWORK::LayerDropout>(0.2));

	// Transition to Dense layers for 16-class classification
	// Input: 128 time steps, 256 channels = 32,768 features (massive feature space!)
	int dense_input_size = 128 * 256;

	// First Dense Layer - High-capacity feature processing
	model.Add(std::make_shared<NEURAL_NETWORK::LayerDense>(
		dense_input_size, // Flattened size: 128×256 = 32,768 features
		1024,             // Large capacity: 1024 neurons for complex 16-class patterns
		0.0, 2e-4         // Moderate L2 for deep network
	));
	model.Add(std::make_shared<NEURAL_NETWORK::ActivationReLU>());

	// Progressive dropout for deep network
	model.Add(std::make_shared<NEURAL_NETWORK::LayerDropout>(0.3));

	// Second Dense Layer - Feature refinement
	model.Add(std::make_shared<NEURAL_NETWORK::LayerDense>(
		1024,             // Input from first dense layer
		512,              // Intermediate capacity: 512 neurons
		0.0, 2e-4         // Consistent L2 regularization
	));
	model.Add(std::make_shared<NEURAL_NETWORK::ActivationReLU>());

	// Stronger dropout before final classification
	model.Add(std::make_shared<NEURAL_NETWORK::LayerDropout>(0.35));

	// Output layer for 16-class modulation classification (EXTREME RESEARCH CHALLENGE)
	model.Add(std::make_shared<NEURAL_NETWORK::LayerDense>(
		512, 16,   // 512 -> 16 classes (updated input size)
		0.0, 2e-4  // Consistent L2 regularization
	));
	model.Add(std::make_shared<NEURAL_NETWORK::ActivationSoftmax>());

	std::cout << "Expected data flow:" << std::endl;
	std::cout << "Input: 2048 -> Conv1D: 1024×64 -> Pool: 512×64 -> Conv1D: 512×128 -> Pool: 256×128 -> Conv1D: 256×256 -> Pool: 128×256 -> Dropout(0.2) -> Dense: 1024 -> ReLU -> Dropout(0.3) -> Dense: 512 -> ReLU -> Dropout(0.35) -> Output: 16 [EXTREME CHALLENGE]" << std::endl;

	// Set up loss, accuracy, and optimizer
	model.Set(
		std::make_unique<NEURAL_NETWORK::LossCategoricalCrossEntropy>(),
		std::make_unique<NEURAL_NETWORK::AccuracyCategorical>(),
		std::make_unique<NEURAL_NETWORK::Adam>(0.00005, 1e-4) // Very low LR for extreme difficulty (0.0001 -> 0.00005)
	);

	model.Finalize();

	std::cout << "\nStarting training on EXTREME 16-class dataset..." << std::endl;
	std::cout << "Expecting 25-45% accuracy due to brutal SNR conditions (-15 to +5 dB)" << std::endl;
	// Train the model with extended epochs for extreme challenge
	model.Train(train_data, y_train, BATCH_SIZE, NN_EPOCHS, NN_PRINT_EVERY, SAVE_EVERY, test_data, y_test);


	// Save the trained model
	std::cout << "\nSaving trained radio modulation model..." << std::endl;
	model.SaveModel("data/radio_modulation_1d_cnn_model.bin");

	std::cout << "\nEvaluating final model on test data:" << std::endl;
	model.Evaluate(test_data, y_test, 32);

	// Example predictions on a few test samples
	std::cout << "\nExample predictions:" << std::endl;
	int num_examples = 10;
	Eigen::MatrixXd sample_data = test_data.topRows(num_examples);
	Eigen::MatrixXd sample_labels = y_test.topRows(num_examples);
	Eigen::MatrixXd predictions = model.Predict(sample_data, 1);

	std::vector<std::string> class_names = {
		"BPSK", "QPSK", "8PSK", "16PSK", "64PSK",          // PSK Family (0-4)
		"16QAM", "32QAM", "64QAM",                         // QAM Family (5-7)
		"ASK", "2FSK", "4FSK", "8FSK",                     // Digital (8-11)
		"GMSK", "MSK", "AM", "FM"                          // Advanced (12-15)
	};
	std::cout << "Predictions vs Actual for first " << num_examples << " test samples:" << std::endl;
	for (int i = 0; i < num_examples; i++) 
	{
		int predicted_class = static_cast<int>(predictions(i, 0));
		int actual_class = static_cast<int>(sample_labels(i, 0));
		std::cout << "Sample " << i << ": Predicted = " << class_names[predicted_class]
				  << ", Actual = " << class_names[actual_class]
				  << (predicted_class == actual_class ? " ✓" : " ✗") << std::endl;
	}

	std::cout << "Model saved to: data/radio_modulation_1d_cnn_model.bin" << std::endl;

	return 0;
}